-- Add organization_id to plagiarism_scan_reports for tenant isolation.
--
-- Before this migration, plagiarism reports had no organization_id column.
-- While the scan submission data was correctly org-scoped at query time, the
-- report list/detail endpoints queried plagiarism_scan_reports without any
-- tenant filter, so a CampusAdmin in org A could list and read reports
-- generated by org B — a cross-tenant data leak of student usernames,
-- submission ids, and similarity pairs.
--
-- We cannot perfectly backfill historical reports (the scan request did not
-- record which org created them), so NULL is allowed and the read queries
-- treat NULL as "only visible to root" as a safe default. All new reports
-- created after this migration are stamped with the caller's organization_id.

ALTER TABLE plagiarism_scan_reports
    ADD COLUMN IF NOT EXISTS organization_id BIGINT;

-- Index for tenant-scoped report listing.
CREATE INDEX IF NOT EXISTS idx_plagiarism_scan_reports_organization
    ON plagiarism_scan_reports(organization_id);
