/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {

        "on-tertiary-container": "#75e8b5",
        "outline": "#737685",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "surface-dim": "#d2d9f4",
        "inverse-primary": "#b2c5ff",
        "on-error-container": "#93000a",
        "primary-container": "#0052cc",
        "inverse-on-surface": "#eef0ff",
        "surface": "#faf8ff",
        "primary-fixed": "#dae2ff",
        "on-tertiary-fixed": "#002114",
        "surface-container": "#eaedff",
        "background": "#faf8ff",
        "on-surface-variant": "#434654",
        "primary-dark": "#0052cc",
        "on-tertiary-fixed-variant": "#005137",
        "tertiary-fixed-dim": "#68dba9",
        "outline-variant": "#c3c6d6",
        "on-secondary-container": "#57657a",
        "on-secondary-fixed": "#0d1c2e",
        "secondary-container": "#d5e3fc",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "secondary-dark": "#515f74",
        "secondary-fixed": "#d5e3fc",
        "surface-tint": "#0c56d0",
        "surface-bright": "#faf8ff",
        "on-primary-container": "#c4d2ff",
        "inverse-surface": "#283044",
        "on-primary-fixed": "#001848",
        "surface-variant": "#dae2fd",
        "on-background": "#131b2e",
        "tertiary": "#004e34",
        "on-secondary-fixed-variant": "#3a485b",
        "secondary-fixed-dim": "#b9c7df",
        "surface-container-high": "#e2e7ff",
        "on-primary": "#ffffff",
        "error-dark": "#ba1a1a",
        "tertiary-fixed": "#85f8c4",
        "surface-container-low": "#f2f3ff",
        "primary-fixed-dim": "#b2c5ff",
        "on-primary-fixed-variant": "#0040a2",
        "on-secondary": "#ffffff",
        "tertiary-container": "#006847",
        "surface-container-highest": "#dae2fd",
        "on-surface": "#131b2e",

              "on-tertiary-container": "#75e8b5",
              "outline": "#737685",
              "surface-container-lowest": "#ffffff",
              "error-container": "#ffdad6",
              "surface-dim": "#d2d9f4",
              "inverse-primary": "#b2c5ff",
              "on-error-container": "#93000a",
              "primary-container": "#0052cc",
              "inverse-on-surface": "#eef0ff",
              "surface": "#faf8ff",
              "primary-fixed": "#dae2ff",
              "on-tertiary-fixed": "#002114",
              "surface-container": "#eaedff",
              "background": "#faf8ff",
              "on-surface-variant": "#434654",
              "primary": "#003d9b",
              "on-tertiary-fixed-variant": "#005137",
              "tertiary-fixed-dim": "#68dba9",
              "outline-variant": "#c3c6d6",
              "on-secondary-container": "#57657a",
              "on-secondary-fixed": "#0d1c2e",
              "secondary-container": "#d5e3fc",
              "on-error": "#ffffff",
              "on-tertiary": "#ffffff",
              "secondary": "#515f74",
              "secondary-fixed": "#d5e3fc",
              "surface-tint": "#0c56d0",
              "surface-bright": "#faf8ff",
              "on-primary-container": "#c4d2ff",
              "inverse-surface": "#283044",
              "on-primary-fixed": "#001848",
              "surface-variant": "#dae2fd",
              "on-background": "#131b2e",
              "tertiary": "#004e34",
              "on-secondary-fixed-variant": "#3a485b",
              "secondary-fixed-dim": "#b9c7df",
              "surface-container-high": "#e2e7ff",
              "on-primary": "#ffffff",
              "error": "#ba1a1a",
              "tertiary-fixed": "#85f8c4",
              "surface-container-low": "#f2f3ff",
              "primary-fixed-dim": "#b2c5ff",
              "on-primary-fixed-variant": "#0040a2",
              "on-secondary": "#ffffff",
              "tertiary-container": "#006847",
              "surface-container-highest": "#dae2fd",
              "on-surface": "#131b2e"
            }
,
fontFamily: {
        display: ['Fira Sans', 'sans-serif'],
        mono: ['Fira Code', 'Monaco', 'Courier New', 'monospace'],
      },
      spacing: {
        0: '0px',
        1: '0.25rem',
        2: '0.5rem',
        3: '0.75rem',
        4: '1rem',
        5: '1.25rem',
        6: '1.5rem',
        8: '2rem',
        10: '2.5rem',
        11: '2.75rem',
        12: '3rem',
        14: '3.5rem',
        16: '4rem',
        20: '5rem',
        24: '6rem',
        32: '8rem',
        40: '10rem',
        64: '16rem',
      },
      fontSize: {
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      boxShadow: {
        sm: '0 1px 2px 0 rgba(15, 23, 42, 0.08)',
        md: '0 6px 18px 0 rgba(15, 23, 42, 0.10)',
        lg: '0 10px 30px 0 rgba(15, 23, 42, 0.14)',
        'primary': '0 4px 14px 0 rgba(13, 89, 242, 0.39)',
      },
      maxWidth: {
        md: '28rem',
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
    },
  },
  plugins: [],
}
