use crate::AppState;
use api_infra::error::AppError;
use axum::{extract::State, http::StatusCode, response::Json, Extension};
use domain_users::{
    models::{LoginRequest as DbLoginRequest, RefreshTokenRequest, RegisterRequest},
    service::UserService,
};
use shared::models::{
    Claims, LoginRequest, LoginResponse, RefreshRequest, RefreshResponse, UserPublic,
};

struct PublicRegistrationScope {
    organization_id: i64,
    campus_id: Option<i64>,
    grade_id: Option<i64>,
}

fn public_registration_scope_from_env() -> Result<Option<PublicRegistrationScope>, AppError> {
    let organization_id = match std::env::var("PUBLIC_REGISTRATION_ORGANIZATION_ID") {
        Ok(value) if !value.trim().is_empty() => value.trim().parse::<i64>().map_err(|_| {
            AppError::Validation("Invalid PUBLIC_REGISTRATION_ORGANIZATION_ID".into())
        })?,
        _ => return Ok(None),
    };

    let campus_id = match std::env::var("PUBLIC_REGISTRATION_CAMPUS_ID") {
        Ok(value) if !value.trim().is_empty() => {
            Some(value.trim().parse::<i64>().map_err(|_| {
                AppError::Validation("Invalid PUBLIC_REGISTRATION_CAMPUS_ID".into())
            })?)
        }
        _ => None,
    };

    let grade_id = match std::env::var("PUBLIC_REGISTRATION_GRADE_ID") {
        Ok(value) if !value.trim().is_empty() => Some(
            value
                .trim()
                .parse::<i64>()
                .map_err(|_| AppError::Validation("Invalid PUBLIC_REGISTRATION_GRADE_ID".into()))?,
        ),
        _ => None,
    };

    Ok(Some(PublicRegistrationScope {
        organization_id,
        campus_id,
        grade_id,
    }))
}

fn normalize_public_register_request(
    mut request: RegisterRequest,
    app_env: api_infra::config::AppEnv,
) -> Result<RegisterRequest, AppError> {
    match public_registration_scope_from_env()? {
        Some(scope) => {
            request.organization_id = scope.organization_id;
            request.campus_id = scope.campus_id;
            request.grade_id = scope.grade_id;
            Ok(request)
        }
        None if app_env.is_production() => Err(AppError::Validation(
            "Public registration is not configured".into(),
        )),
        None => {
            tracing::warn!(
                "PUBLIC_REGISTRATION_ORGANIZATION_ID is not set; trusting registration tenant fields in non-production only"
            );
            Ok(request)
        }
    }
}

fn make_cookie_header(name: &str, value: &str, max_age: u32, path: &str, secure: bool) -> String {
    let mut cookie = format!(
        "{}={}; HttpOnly; SameSite=Strict; Path={}; Max-Age={}",
        name, value, path, max_age
    );
    if secure {
        cookie.push_str("; Secure");
    }
    cookie
}

pub async fn login(
    State(state): State<AppState>,
    Json(request): Json<LoginRequest>,
) -> Result<(axum::http::HeaderMap, Json<LoginResponse>), StatusCode> {
    let service = UserService::new(state.db_pool.clone(), state.jwt_service.clone());
    let response = service
        .login(DbLoginRequest {
            username: request.username,
            password: request.password,
        })
        .await
        .map_err(|_| StatusCode::UNAUTHORIZED)?;

    // Track refresh token JTI in Redis so we can revoke it on logout
    track_refresh_token(&state, &response.refresh_token).await;

    let mut headers = axum::http::HeaderMap::new();
    let secure = state.app_env.is_production();
    headers.insert(
        axum::http::header::SET_COOKIE,
        make_cookie_header("access_token", &response.token, 14400, "/", secure)
            .parse()
            .expect("cookie header generated by make_cookie_header is always valid ASCII"),
    );
    headers.insert(
        axum::http::header::SET_COOKIE,
        make_cookie_header(
            "refresh_token",
            &response.refresh_token,
            604800,
            "/api/auth/refresh",
            secure,
        )
        .parse()
        .expect("cookie header generated by make_cookie_header is always valid ASCII"),
    );

    Ok((
        headers,
        Json(LoginResponse {
            token: response.token,
            refresh_token: response.refresh_token,
            user: UserPublic {
                id: response.user.id,
                user_code: response.user.user_code,
                username: response.user.username,
                email: response.user.email.unwrap_or_default(),
                display_name: response.user.display_name,
                role: response.user.role,
                school_id: response.user.organization_id,
                campus_id: response.user.campus_id,
                grade_id: response.user.grade_id,
            },
        }),
    ))
}

pub async fn refresh(
    State(state): State<AppState>,
    headers: axum::http::HeaderMap,
    Json(request): Json<RefreshRequest>,
) -> Result<(axum::http::HeaderMap, Json<RefreshResponse>), StatusCode> {
    // Try cookie first, then body
    let refresh_token = headers
        .get("cookie")
        .and_then(|c| c.to_str().ok())
        .and_then(|c| {
            c.split(';').find_map(|cookie| {
                let parts: Vec<&str> = cookie.trim().splitn(2, '=').collect();
                if parts.len() == 2 && parts[0] == "refresh_token" {
                    Some(parts[1].to_string())
                } else {
                    None
                }
            })
        })
        .or(request.refresh_token);

    let refresh_token = refresh_token.ok_or(StatusCode::UNAUTHORIZED)?;

    // Check if refresh token has been revoked (blacklisted)
    if is_refresh_token_revoked(&state, &refresh_token).await {
        tracing::warn!("Refresh token rejected — JTI has been revoked (logout)");
        return Err(StatusCode::UNAUTHORIZED);
    }

    let service = UserService::new(state.db_pool.clone(), state.jwt_service.clone());
    let response = service
        .refresh_token(RefreshTokenRequest {
            refresh_token: refresh_token.clone(),
        })
        .await
        .map_err(|_| StatusCode::UNAUTHORIZED)?;

    let mut resp_headers = axum::http::HeaderMap::new();
    let secure = state.app_env.is_production();
    resp_headers.insert(
        axum::http::header::SET_COOKIE,
        make_cookie_header("access_token", &response.token, 14400, "/", secure)
            .parse()
            .expect("cookie header generated by make_cookie_header is always valid ASCII"),
    );

    Ok((
        resp_headers,
        Json(RefreshResponse {
            token: response.token,
        }),
    ))
}

pub async fn logout(
    Extension(claims): Extension<Claims>,
    State(state): State<AppState>,
    headers: axum::http::HeaderMap,
) -> (axum::http::HeaderMap, StatusCode) {
    // Blacklist access token JTI
    let ttl = claims.exp - chrono::Utc::now().timestamp();
    if ttl > 0 {
        if let Some(redis_pool) = &state.redis_pool {
            if let Ok(mut conn) = redis_pool.get().await {
                let _: () = deadpool_redis::redis::cmd("SET")
                    .arg(format!("bl:{}", claims.jti))
                    .arg("1")
                    .arg("EX")
                    .arg(ttl)
                    .query_async(&mut conn)
                    .await
                    .unwrap_or(());
            }
        }

        if let Err(err) = revoke_jti_in_db(&state, &claims, "access").await {
            tracing::error!(
                user_id = %claims.sub,
                error = %err,
                "Failed to persist access token revocation"
            );
        }
    }

    // Also revoke the refresh token if present (in cookie or already decoded)
    if let Some(refresh_token_str) = extract_refresh_token_from_headers(&headers) {
        revoke_refresh_token(&state, &refresh_token_str).await;
    }

    let secure = state.app_env.is_production();
    let mut response_headers = axum::http::HeaderMap::new();
    response_headers.append(
        axum::http::header::SET_COOKIE,
        make_cookie_header("access_token", "", 0, "/", secure)
            .parse()
            .expect("cookie header generated by make_cookie_header is always valid ASCII"),
    );
    response_headers.append(
        axum::http::header::SET_COOKIE,
        make_cookie_header("refresh_token", "", 0, "/api/auth/refresh", secure)
            .parse()
            .expect("cookie header generated by make_cookie_header is always valid ASCII"),
    );

    (response_headers, StatusCode::OK)
}

pub async fn register(
    State(state): State<AppState>,
    Json(request): Json<RegisterRequest>,
) -> Result<
    (
        axum::http::HeaderMap,
        Json<domain_users::models::AuthResponse>,
    ),
    AppError,
> {
    let request = normalize_public_register_request(request, state.app_env)?;
    let service = UserService::new(state.db_pool.clone(), state.jwt_service.clone());
    let profile = service.register(request).await.map_err(|err| {
        tracing::warn!(error = %err, "registration rejected");
        AppError::Validation(err.to_string())
    })?;

    let shared_user = shared::models::User {
        id: profile.id,
        username: profile.username.clone(),
        email: profile.email.clone().unwrap_or_default(),
        password_hash: String::new(),
        role: profile.role.clone(),
        school_id: profile.organization_id,
        campus_id: profile.campus_id,
        grade_id: profile.grade_id,
    };

    let token = state
        .jwt_service
        .generate_access_token(&shared_user)
        .map_err(|err| AppError::Internal(err.to_string()))?;
    let refresh_token = state
        .jwt_service
        .generate_refresh_token(&shared_user)
        .map_err(|err| AppError::Internal(err.to_string()))?;

    // Track refresh token JTI in Redis so we can revoke it on logout
    track_refresh_token(&state, &refresh_token).await;

    let mut headers = axum::http::HeaderMap::new();
    let secure = state.app_env.is_production();
    headers.insert(
        axum::http::header::SET_COOKIE,
        make_cookie_header("access_token", &token, 14400, "/", secure)
            .parse()
            .expect("cookie header generated by make_cookie_header is always valid ASCII"),
    );
    headers.insert(
        axum::http::header::SET_COOKIE,
        make_cookie_header(
            "refresh_token",
            &refresh_token,
            604800,
            "/api/auth/refresh",
            secure,
        )
        .parse()
        .expect("cookie header generated by make_cookie_header is always valid ASCII"),
    );

    Ok((
        headers,
        Json(domain_users::models::AuthResponse {
            token,
            refresh_token,
            user: profile,
        }),
    ))
}

/// Redis key prefix for refresh token tracking. 30-day TTL matches REFRESH_TOKEN_EXPIRATION_DAYS.
const REFRESH_TOKEN_TTL_SECS: i64 = 30 * 24 * 60 * 60; // 2_592_000 seconds

/// Store refresh token JTI in Redis with a 30-day TTL so it can be revoked on logout.
async fn track_refresh_token(state: &AppState, refresh_token: &str) {
    if let Some(redis_pool) = &state.redis_pool {
        let claims = match state.jwt_service.validate_token(refresh_token) {
            Ok(c) => c,
            Err(_) => return,
        };
        let remaining_secs = claims.exp - chrono::Utc::now().timestamp();
        if remaining_secs <= 0 {
            return;
        }
        let ttl = remaining_secs.min(REFRESH_TOKEN_TTL_SECS);
        if let Ok(mut conn) = redis_pool.get().await {
            let _: () = deadpool_redis::redis::cmd("SET")
                .arg(format!("rt:{}", claims.jti))
                .arg("1")
                .arg("EX")
                .arg(ttl)
                .query_async(&mut conn)
                .await
                .unwrap_or(());
        }
    } else if state.app_env.is_production() {
        tracing::warn!(
            "Redis is not configured in production; refresh-token tracking relies on database revocation fallback"
        );
    }
}

/// Check if a refresh token has been revoked via blacklist.
async fn is_refresh_token_revoked(state: &AppState, refresh_token: &str) -> bool {
    let claims = match state.jwt_service.validate_token(refresh_token) {
        Ok(c) => c,
        Err(_) => return true, // Invalid token = treat as revoked
    };

    if let Some(redis_pool) = &state.redis_pool {
        match redis_pool.get().await {
            Ok(mut conn) => {
                let blacklisted: bool = deadpool_redis::redis::cmd("EXISTS")
                    .arg(format!("bl:{}", claims.jti))
                    .query_async(&mut conn)
                    .await
                    .unwrap_or(false);
                if blacklisted {
                    tracing::info!(
                        user_id = %claims.sub,
                        "Refresh token revoked — JTI found in blacklist"
                    );
                }
                blacklisted
            }
            Err(e) => {
                // Fail-closed: if Redis is unavailable, treat as revoked
                tracing::warn!(
                    "Redis unavailable during refresh token blacklist check — rejecting (fail-closed): {}",
                    e
                );
                true
            }
        }
    } else {
        is_jti_revoked_in_db(state, claims.jti).await
    }
}

/// Revoke a refresh token by blacklisting its JTI on logout.
async fn revoke_refresh_token(state: &AppState, refresh_token: &str) {
    let claims = match state.jwt_service.validate_token(refresh_token) {
        Ok(c) => c,
        Err(_) => return,
    };
    let remaining_secs = claims.exp - chrono::Utc::now().timestamp();
    if remaining_secs <= 0 {
        return;
    }

    if let Some(redis_pool) = &state.redis_pool {
        if let Ok(mut conn) = redis_pool.get().await {
            let _: () = deadpool_redis::redis::cmd("SET")
                .arg(format!("bl:{}", claims.jti))
                .arg("1")
                .arg("EX")
                .arg(remaining_secs)
                .query_async(&mut conn)
                .await
                .unwrap_or(());
            tracing::info!(
                user_id = %claims.sub,
                "Refresh token revoked on logout — JTI blacklisted"
            );
        }
    }

    if let Err(err) = revoke_jti_in_db(state, &claims, "refresh").await {
        tracing::error!(
            user_id = %claims.sub,
            error = %err,
            "Failed to persist refresh token revocation"
        );
    }
}

pub(crate) async fn is_jti_revoked_in_db(state: &AppState, jti: uuid::Uuid) -> bool {
    match sqlx::query_scalar::<_, bool>(
        "SELECT EXISTS(SELECT 1 FROM token_revocations WHERE jti = $1 AND expires_at > NOW())",
    )
    .bind(jti)
    .fetch_one(&state.db_pool)
    .await
    {
        Ok(revoked) => revoked,
        Err(err) => {
            tracing::warn!(
                error = %err,
                "Database unavailable during token revocation check — rejecting (fail-closed)"
            );
            true
        }
    }
}

pub(crate) async fn revoke_jti_in_db(
    state: &AppState,
    claims: &Claims,
    token_type: &str,
) -> Result<(), sqlx::Error> {
    let expires_at = chrono::DateTime::<chrono::Utc>::from_timestamp(claims.exp, 0)
        .unwrap_or_else(chrono::Utc::now);
    sqlx::query(
        r#"
        INSERT INTO token_revocations (jti, user_id, token_type, expires_at)
        VALUES ($1, $2, $3, $4)
        ON CONFLICT (jti) DO UPDATE
        SET expires_at = EXCLUDED.expires_at,
            token_type = EXCLUDED.token_type
        "#,
    )
    .bind(claims.jti)
    .bind(claims.sub)
    .bind(token_type)
    .bind(expires_at)
    .execute(&state.db_pool)
    .await?;

    Ok(())
}

/// Extract refresh token string from cookie header.
fn extract_refresh_token_from_headers(headers: &axum::http::HeaderMap) -> Option<String> {
    headers
        .get("cookie")
        .and_then(|c| c.to_str().ok())
        .and_then(|c| {
            c.split(';').find_map(|cookie| {
                let parts: Vec<&str> = cookie.trim().splitn(2, '=').collect();
                if parts.len() == 2 && parts[0] == "refresh_token" {
                    Some(parts[1].to_string())
                } else {
                    None
                }
            })
        })
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::{
        body::Body,
        http::{header, Request, StatusCode},
        routing::post,
        Router,
    };
    use tower::ServiceExt;

    static ENV_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

    fn sample_register_request() -> RegisterRequest {
        RegisterRequest {
            user_code: Some("100100000123".to_string()),
            username: "100100000123".to_string(),
            password: "password123".to_string(),
            email: Some("student@example.com".to_string()),
            display_name: Some("Student".to_string()),
            organization_id: 999,
            campus_id: Some(998),
            grade_id: Some(997),
        }
    }

    #[test]
    fn public_registration_scope_overrides_client_tenant_fields() {
        let _guard = ENV_LOCK.lock().unwrap();
        std::env::set_var("PUBLIC_REGISTRATION_ORGANIZATION_ID", "10");
        std::env::set_var("PUBLIC_REGISTRATION_CAMPUS_ID", "20");
        std::env::set_var("PUBLIC_REGISTRATION_GRADE_ID", "30");

        let request = normalize_public_register_request(
            sample_register_request(),
            api_infra::config::AppEnv::Production,
        )
        .expect("configured public registration should be accepted");

        assert_eq!(request.organization_id, 10);
        assert_eq!(request.campus_id, Some(20));
        assert_eq!(request.grade_id, Some(30));

        std::env::remove_var("PUBLIC_REGISTRATION_ORGANIZATION_ID");
        std::env::remove_var("PUBLIC_REGISTRATION_CAMPUS_ID");
        std::env::remove_var("PUBLIC_REGISTRATION_GRADE_ID");
    }

    #[test]
    fn public_registration_fails_closed_in_production_without_scope() {
        let _guard = ENV_LOCK.lock().unwrap();
        std::env::remove_var("PUBLIC_REGISTRATION_ORGANIZATION_ID");
        std::env::remove_var("PUBLIC_REGISTRATION_CAMPUS_ID");
        std::env::remove_var("PUBLIC_REGISTRATION_GRADE_ID");

        let err = normalize_public_register_request(
            sample_register_request(),
            api_infra::config::AppEnv::Production,
        )
        .expect_err("production public registration must require server-side scope");

        match err {
            AppError::Validation(message) => {
                assert!(message.contains("Public registration is not configured"));
            }
            _ => panic!("expected validation error"),
        }
    }

    async fn create_test_app() -> Router {
        use crate::auth::JwtService;

        let jwt_secret =
            std::env::var("JWT_SECRET").unwrap_or_else(|_| "test_secret_key".to_string());

        let jwt_service = JwtService::new(&jwt_secret);

        let database_url = match std::env::var("DATABASE_URL") {
            Ok(url) if !url.is_empty() => url,
            _ => {
                panic!("DATABASE_URL must be set for auth route tests");
            }
        };

        let db_pool = sqlx::PgPool::connect(&database_url)
            .await
            .expect("Failed to create test database pool");

        let app_state = crate::AppState {
            db_pool: db_pool.clone(),
            redis_pool: None,
            jwt_service: std::sync::Arc::new(jwt_service),
            redis_url: String::new(),
            jwt_secret: jwt_secret.clone(),
            worker_secret: "test_worker_secret".to_string(),
            websocket_server: std::sync::Arc::new(crate::websocket::WebSocketServer::new()),
            class_membership_checker: std::sync::Arc::new(
                api_infra::traits::class_repo::NoopClassMembershipChecker,
            ),
            prometheus_handle: api_infra::metrics::setup_metrics_recorder(),
            preview_cache: std::sync::Arc::new(dashmap::DashMap::new()),
            gateway_client: std::sync::Arc::new(api_infra::feature_gateway::GatewayClient::new(
                "http://127.0.0.1:3001".to_string(),
                "test_secret".to_string(),
            )),
            app_env: api_infra::config::AppEnv::Test,
        };

        Router::new()
            .route("/login", post(login))
            .route("/refresh", post(refresh))
            .route("/logout", post(logout))
            .route("/register", post(register))
            .with_state(app_state)
    }

    #[ignore = "requires a running PostgreSQL database; set DATABASE_URL environment variable"]
    #[tokio::test]
    async fn test_login_invalid_credentials() {
        let app = create_test_app().await;

        let response = app
            .oneshot(
                Request::builder()
                    .method("POST")
                    .uri("/login")
                    .header(header::CONTENT_TYPE, "application/json")
                    .body(Body::from(
                        r#"{"username": "9999", "password": "wrong_password"}"#,
                    ))
                    .unwrap(),
            )
            .await
            .unwrap();

        assert_eq!(response.status(), StatusCode::UNAUTHORIZED);
    }

    /// Seed a demo admin user (username "1001", password "admin123") for integration tests.
    async fn seed_demo_admin() {
        let database_url = std::env::var("DATABASE_URL").expect("DATABASE_URL must be set");
        let pool = sqlx::PgPool::connect(&database_url)
            .await
            .expect("Failed to connect to seed DB");

        // Ensure organization exists
        sqlx::query("INSERT INTO organizations (id, name, slug) VALUES (1, 'Test Org', 'test-org') ON CONFLICT (id) DO NOTHING")
            .execute(&pool)
            .await
            .expect("Failed to seed organization");

        // Hash password
        let password_hash =
            bcrypt::hash("admin123", bcrypt::DEFAULT_COST).expect("Failed to hash password");

        // Insert user (idempotent via ON CONFLICT)
        sqlx::query(
            r#"INSERT INTO users (username, email, password_hash, display_name, user_code, organization_id, status)
            VALUES ('1001', 'admin@example.com', $1, 'Demo Admin', '100100000001', 1, 'active')
            ON CONFLICT (username) DO NOTHING"#,
        )
        .bind(&password_hash)
        .execute(&pool)
        .await
        .expect("Failed to seed demo admin user");

        // Insert user_role (idempotent)
        let user_id: Option<uuid::Uuid> =
            sqlx::query_scalar("SELECT id FROM users WHERE username = '1001'")
                .fetch_optional(&pool)
                .await
                .expect("Failed to query demo admin")
                .flatten();

        if let Some(uid) = user_id {
            sqlx::query(
                "INSERT INTO user_roles (user_id, organization_id, campus_id, grade_id, role)
                VALUES ($1, 1, NULL, NULL, 'root')
                ON CONFLICT DO NOTHING",
            )
            .bind(uid)
            .execute(&pool)
            .await
            .expect("Failed to seed demo admin role");
        }
    }

    #[ignore = "requires a running PostgreSQL database; set DATABASE_URL environment variable"]
    #[tokio::test]
    async fn test_login_valid_credentials() {
        std::env::set_var("JWT_SECRET", "test_secret_key");
        seed_demo_admin().await;

        let app = create_test_app().await;

        let response = app
            .oneshot(
                Request::builder()
                    .method("POST")
                    .uri("/login")
                    .header(header::CONTENT_TYPE, "application/json")
                    .body(Body::from(
                        r#"{"username": "1001", "password": "admin123"}"#,
                    ))
                    .unwrap(),
            )
            .await
            .unwrap();

        assert_eq!(response.status(), StatusCode::OK);

        let body = axum::body::to_bytes(response.into_body(), usize::MAX)
            .await
            .unwrap();
        let json_response: serde_json::Value = serde_json::from_slice(&body).unwrap();

        assert!(json_response["token"].is_string());
        assert!(json_response["refresh_token"].is_string());
        assert_eq!(json_response["user"]["username"], "1001");
        assert_eq!(json_response["user"]["school_id"], 1);
    }

    #[ignore = "requires a running PostgreSQL database; set DATABASE_URL environment variable"]
    #[tokio::test]
    async fn test_refresh_invalid_token() {
        let app = create_test_app().await;

        let response = app
            .oneshot(
                Request::builder()
                    .method("POST")
                    .uri("/refresh")
                    .header(header::CONTENT_TYPE, "application/json")
                    .body(Body::from(r#"{"refresh_token": "invalid_token"}"#))
                    .unwrap(),
            )
            .await
            .unwrap();

        assert_eq!(response.status(), StatusCode::UNAUTHORIZED);
    }

    #[ignore = "requires a running PostgreSQL database; set DATABASE_URL environment variable"]
    #[tokio::test]
    async fn test_refresh_valid_token() {
        std::env::set_var("JWT_SECRET", "test_secret_key");
        seed_demo_admin().await;

        let app = create_test_app().await;

        let login_response = app
            .clone()
            .oneshot(
                Request::builder()
                    .method("POST")
                    .uri("/login")
                    .header(header::CONTENT_TYPE, "application/json")
                    .body(axum::body::Body::from(
                        r#"{"username": "1001", "password": "admin123"}"#,
                    ))
                    .unwrap(),
            )
            .await
            .unwrap();

        assert_eq!(login_response.status(), StatusCode::OK);

        let login_body = axum::body::to_bytes(login_response.into_body(), usize::MAX)
            .await
            .unwrap();
        let login_json: serde_json::Value = serde_json::from_slice(&login_body).unwrap();

        let refresh_token = login_json["refresh_token"].as_str().unwrap();

        let refresh_response = app
            .clone()
            .oneshot(
                Request::builder()
                    .method("POST")
                    .uri("/refresh")
                    .header(header::CONTENT_TYPE, "application/json")
                    .body(axum::body::Body::from(format!(
                        r#"{{"refresh_token": "{}"}}"#,
                        refresh_token
                    )))
                    .unwrap(),
            )
            .await
            .unwrap();

        assert_eq!(refresh_response.status(), StatusCode::OK);

        let refresh_body = axum::body::to_bytes(refresh_response.into_body(), usize::MAX)
            .await
            .unwrap();
        let refresh_json: serde_json::Value = serde_json::from_slice(&refresh_body).unwrap();

        assert!(refresh_json["token"].is_string());
    }

    #[tokio::test]
    async fn test_logout_returns_ok() {
        let claims = Claims {
            sub: uuid::Uuid::new_v4(),
            email: "test@example.com".to_string(),
            role: "student".to_string(),
            school_id: 1,
            campus_id: None,
            grade_id: None,
            iat: chrono::Utc::now().timestamp(),
            exp: chrono::Utc::now().timestamp() + 3600,
            jti: uuid::Uuid::new_v4(),
        };
        let state = crate::AppState {
            db_pool: sqlx::PgPool::connect_lazy("postgres://localhost/nonexistent").unwrap(),
            redis_pool: None,
            jwt_service: std::sync::Arc::new(crate::auth::JwtService::new("test_secret")),
            redis_url: String::new(),
            jwt_secret: "test_secret".to_string(),
            worker_secret: "test_worker_secret".to_string(),
            websocket_server: std::sync::Arc::new(crate::websocket::WebSocketServer::new()),
            class_membership_checker: std::sync::Arc::new(
                api_infra::traits::class_repo::NoopClassMembershipChecker,
            ),
            prometheus_handle: api_infra::metrics::setup_metrics_recorder(),
            preview_cache: std::sync::Arc::new(dashmap::DashMap::new()),
            gateway_client: std::sync::Arc::new(api_infra::feature_gateway::GatewayClient::new(
                "http://127.0.0.1:3001".to_string(),
                "test_secret".to_string(),
            )),
            app_env: api_infra::config::AppEnv::Test,
        };
        let empty_headers = axum::http::HeaderMap::new();
        let (headers, status) = logout(Extension(claims), State(state), empty_headers).await;
        assert_eq!(status, StatusCode::OK);
        let cookies = headers
            .get_all(axum::http::header::SET_COOKIE)
            .iter()
            .filter_map(|value| value.to_str().ok())
            .collect::<Vec<_>>();
        assert!(cookies
            .iter()
            .any(|cookie| cookie.starts_with("access_token=")));
        assert!(cookies
            .iter()
            .any(|cookie| cookie.starts_with("refresh_token=")));
    }

    #[ignore = "requires a running PostgreSQL database; set DATABASE_URL environment variable"]
    #[tokio::test]
    async fn test_register_rejects_grade_from_other_campus() {
        let app = create_test_app().await;
        let database_url = std::env::var("DATABASE_URL").expect("DATABASE_URL must be set");
        let pool = sqlx::PgPool::connect(&database_url)
            .await
            .expect("Failed to connect to seed DB");

        let org_a: i64 = sqlx::query_scalar(
            "INSERT INTO organizations (name, slug) VALUES ('Register Org A', 'register-org-a') RETURNING id",
        )
        .fetch_one(&pool)
        .await
        .expect("failed to insert org A");
        let campus_a: i64 = sqlx::query_scalar(
            "INSERT INTO campuses (organization_id, name, slug) VALUES ($1, 'Campus A', 'campus-a') RETURNING id",
        )
        .bind(org_a)
        .fetch_one(&pool)
        .await
        .expect("failed to insert campus A");
        let _grade_a: i64 = sqlx::query_scalar(
            "INSERT INTO grades (campus_id, name, year_level, academic_year) VALUES ($1, 'Grade A', 1, '2025-2026') RETURNING id",
        )
        .bind(campus_a)
        .fetch_one(&pool)
        .await
        .expect("failed to insert grade A");

        let org_b: i64 = sqlx::query_scalar(
            "INSERT INTO organizations (name, slug) VALUES ('Register Org B', 'register-org-b') RETURNING id",
        )
        .fetch_one(&pool)
        .await
        .expect("failed to insert org B");
        let campus_b: i64 = sqlx::query_scalar(
            "INSERT INTO campuses (organization_id, name, slug) VALUES ($1, 'Campus B', 'campus-b') RETURNING id",
        )
        .bind(org_b)
        .fetch_one(&pool)
        .await
        .expect("failed to insert campus B");
        let grade_b: i64 = sqlx::query_scalar(
            "INSERT INTO grades (campus_id, name, year_level, academic_year) VALUES ($1, 'Grade B', 1, '2025-2026') RETURNING id",
        )
        .bind(campus_b)
        .fetch_one(&pool)
        .await
        .expect("failed to insert grade B");

        let body = serde_json::json!({
            "user_code": "100100000123",
            "username": "100100000123",
            "password": "password123",
            "email": "student@example.com",
            "display_name": "Student",
            "organization_id": org_a,
            "campus_id": campus_a,
            "grade_id": grade_b,
        })
        .to_string();

        let response = app
            .oneshot(
                Request::builder()
                    .method("POST")
                    .uri("/register")
                    .header(header::CONTENT_TYPE, "application/json")
                    .body(Body::from(body))
                    .unwrap(),
            )
            .await
            .unwrap();

        assert_eq!(
            response.status(),
            StatusCode::BAD_REQUEST,
            "grade_id from another campus must be rejected"
        );
    }

    #[test]
    fn test_make_cookie_header_without_secure() {
        let cookie = make_cookie_header("access_token", "tok123", 14400, "/", false);
        assert!(
            !cookie.contains("Secure"),
            "cookie should NOT contain Secure flag when secure=false: {}",
            cookie
        );
        assert!(cookie.contains("HttpOnly"));
        assert!(cookie.contains("SameSite=Strict"));
    }

    #[test]
    fn test_make_cookie_header_with_secure() {
        let cookie = make_cookie_header("access_token", "tok123", 14400, "/", true);
        assert!(
            cookie.contains("; Secure"),
            "cookie SHOULD contain Secure flag when secure=true: {}",
            cookie
        );
        assert!(cookie.contains("HttpOnly"));
        assert!(cookie.contains("SameSite=Strict"));
    }
}
